source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'DearZoo_iOS' do
	
  pod 'Parse'

end

target 'DearZoo_iOSTests' do

end

target 'DearZoo_iOSUITests' do

end

